### PR TITLE
Document that a production tier plan is required to use SSL

### LINKED ISSUE #16: Document that the buildpack requires a production Heroku Redis plan
TLS isn't supported for the hobby/dev plans, and whilst this is mentioned here:
https://devcenter.heroku.com/articles/securing-heroku-redis

...it would be good to add this to the README too :-)

### PR DESCRIPTION
**Pull request by edmorley**
Fixes #16.

### CODE REVIEW

**Comment by edmorley** [comment]
The comparison charts on https://elements.heroku.com/addons/heroku-redis could also do with having SSL listed.

**Comment by edmorley** [comment]
@neovintage, hi! I don't suppose you know when you might be able to review this? :-)

**Comment by edmorley** [comment]
@cyberdelia, mind taking a look? :-)

**Comment by cyberdelia** [comment]
@edmorley And again, thanks :bowtie:

**Pull request merged**
