### PR TITLE
Use stack image binary

### PR DESCRIPTION
**Pull request by tt**
With heroku/stack-images#17 merged, this should work. I'm going to test this later and will report back.

### CODE REVIEW

**Comment by cyberdelia** [comment]
@tt This doesn't support cedar-10 right?

**Comment by tt** [comment]
It should.

**Comment by cyberdelia** [comment]
@tt Is stunnel also available on cedar-10 now?

**Comment by tt** [comment]
Yes.

**Comment by cyberdelia** [comment]
I fixed a couple of issue, but this got merged.

**Comment by cyberdelia** [comment]
Thanks @tt!

**Pull request closed without merging**
